### ISSUE TITLE
 error MSB4184:  Pathexceeds the OS max path limit.

### ISSUE THREAD

**Issue by vindhya124** [luiz-dnx/DotNetFrameworkApp#1]
I am getting below error when i am trying the AWs code build.

C:\Program Files\dotnet\sdk\7.0.100\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.Sdk.targets(44,5): error MSB4184: The expression "[MSBuild]::NormalizePath(C:\codebuild\tmp\output\src047448063\src\codestar-connections.us-east-2.amazonaws.com\git-http\515634680606\us-east-2\47f2ae13-7889-4ef5-88d8-32a2d82ed5db\Givealittle\GivealittleV4\Src\Common\Common, obj\Debug\netstandard2.0\Givealittle.Common.genruntimeconfig.cache)" cannot be evaluated. Path: C:\codebuild\tmp\output\src047448063\src\codestar-connections.us-east-2.amazonaws.com\git-http\515634680606\us-east-2\47f2ae13-7889-4ef5-88d8-32a2d82ed5db\Givealittle\GivealittleV4\Src\Common\Common\obj\Debug\netstandard2.0\Givealittle.Common.genruntimeconfig.cache exceeds the OS max path limit. The fully qualified file name must be less than 260 characters. [C:\codebuild\tmp\output\src047448063\src\codestar-connections.us-east-2.amazonaws.com\git-http\515634680606\us-east-2\47f2ae13-7889-4ef5-88d8-32a2d82ed5db\Givealittle\GivealittleV4\Src\Common\Common\Givealittle.Common.csproj]

Did you faced any of the issues before?

**Comment by luizfds** [comment]
Hi @vindhya124,
No, I haven't. Have you followed all the steps described [here](https://medium.com/@luizfds/automating-net-framework-deployments-with-aws-codepipeline-to-elastic-beanstalk-e21abba39ad3)?

I will try to deploy this app again and see if I get the same error.

**Comment by vindhya124** [comment]
Hi @luiz-dnx ,

Yes i have did the same steps in AWS code build but i think i have along project name which is causing this problem

**Comment by luizfds** [comment]
Yep, that might be the reason. Have a look at this StackOverflow [link](https://stackoverflow.com/questions/11434206/visual-studio-unknown-build-error-the-fully-qualified-name-must-be-less-than-26) or this [issue](https://github.com/microsoft/dotnet/issues/234).

**Comment by vindhya124** [comment]
cool thank you. Please let me know if you find any possible solutions.

**Comment by vindhya124** [comment]
Hi 

As per below sample solution I am able to fix the long path issue.

https://github.com/aws-quickstart/quickstart-dotnet-serverless-cicd/blob/main/buildspec.yml

Thanks

**Comment by luizfds** [comment]
Awesome! Neat and simple solution. 👏🏼
